"""update orm models

Revision ID: 1ba1b60fdc32
Revises: cffadbf9f43d
Create Date: 2026-10-09 03:24:34.854603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba1b60fdc32'
down_revision: Union[str, Sequence[str], None] = 'cffadbf9f43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'updated_at')
    # ### end Alembic commands ###
